###服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-t248-weixin
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

####swagger相关配置
swagger:
  base-package: com.t248.weixin.service
  title: 微信服务接口
  description: Spring Cloud项目实践
  version: 1.1
  contact:
    name: 风继续吹
    email: 1366845556@qq.com

